### ISSUE TITLE
Serialization No Longer Allows float("inf") for float32 Type

### ISSUE THREAD

**Issue by connoranderson** [ros2/rosidl_python#169]
In galactic release, we were able to use the numeric-limit value of float("inf") for a float32 type. When https://github.com/ros2/rosidl_python/pull/128 was introduced (and subsequently we began experimenting with humble release), we observed that the numeric limit checks prevented this use case. This is creating inconsistencies as our c++ code is still able to serialize using `std::numeric_limits<T>::infinity` but the python code is not able to do so. 

## Bug report

**Required Info:**

- Operating System:
  - ubuntu 22.04
- Installation type:
  - binaries
- Version or commit hash:
  - humble
- DDS implementation:
  - not relevant
- Client library (if applicable):
  - rclpy

#### Steps to reproduce issue
``` 
my_msg = Msg() # info field is float32
my_msg.info = float("inf")
```

#### Expected behavior
Set my_msg.info to INF (formerly would serialize to 3.402823e+40 in galactic)

#### Actual behavior
```
AssertionError: The 'info' field must be a float in [-3.402823e+38, 3.402823e+38]
```

**Comment by maspe36** [comment]
This is also a problem for `float("nan")`

**Comment by sloretz** [comment]
Thanks for the report! The problem with `nan` was reported in #162, and #167 should fix both that and this issue.

**Comment by connoranderson** [comment]
@sloretz sounds good. Can we make sure that PR gets a backport to humble release?

**Comment by connoranderson** [comment]
@sloretz is there an ETA expected for #167 to merge?

**Comment by connoranderson** [comment]
@sloretz do you think this will be backported to humble? Looks like there was a windows compatibility issue, as well, so just want to make sure that this fix finds its way to humble.

**Comment by aditya2592** [comment]
Hi, will this fix be backported to Humble?

**Comment by clalancette** [comment]
> Hi, will this fix be backported to Humble?

Yes, it's already done via https://github.com/ros2/rosidl_python/pull/188 , and will be in the next patch release (later this month).
