### ISSUE TITLE
Get public property names through method or public property (i.e. public __slots__)

### ISSUE THREAD

**Issue by brawner** [ros2/rosidl_python#20]
I'm running into this use case porting rqt_publisher. It inspects the message class to get slot names and types (PR #19)  and fills the message with appropriate values. Currently, __slots__ points to the private fields _data, etc so setting those values directly may lead the user to fill in a message with invalid types. 

```
>>> from std_msgs.msg import Float64
>>> f = Float64()
>>> for slot_name in f.__slots__:
...   setattr(f, slot_name, str(1))
... 
>>> 
```

In rqt_publisher, I would like to catch the ValueError if they try to set the property with a bad type and warn the user. 

However, to do so with inspection like I'm doing, I would need one of the following (in order of preference):
1). A public slots property or getter to point to the public properties of a message instance
2). A pointer from the private field to the public property (and vice versa)
3). My own logic which manipulates private slot_names to get the property name.

**Comment by dirk-thomas** [comment]
Maybe updating the referenced PR to provide a dictionary mapping field names (without the leading underscore) to their type would be best?

**Comment by brawner** [comment]
@mlautman Do you have any input?

**Comment by dirk-thomas** [comment]
A message class provides the class method `get_fields_and_field_types` which returns a dictionary mapping field names (without a leading underscore) to the field type.
