### ISSUE TITLE
Erroneous mypy specifications

### ISSUE THREAD

**Issue by artivis** [ros2/rosidl_python#70]
Edit:
I've been using `import_message_from_namespaced_type` wrong due to misleading erroneous mypy specifications
```python
def import_message_from_namespaced_type(message_type: NamespacedType)
```

Leaving this issue open until the specification get fixed.

Original:
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - source
- Version or commit hash:
  - 2d8af1e0fbb120dd9101ca620c24c59e940d1be6
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - rclpy

#### Steps to reproduce issue

```python
from rosidl_parser.definition import NamespacedType
from rosidl_runtime_py.import_message import import_message_from_namespaced_type

message = import_message_from_namespaced_type(
            NamespacedType(['std_msgs', 'msg'], 'Bool'))
```

#### Expected behavior
Imports a `std_msgs/msg/Bool`
#### Actual behavior
Crash
```terminal
AttributeError: 'NamespacedType' object has no attribute 'value_type'
```
#### Additional information

Crash comes from [`import_message_from_namespaced_type`](https://github.com/ros2/rosidl_python/blob/master/rosidl_runtime_py/rosidl_runtime_py/import_message.py#L23) which expects a [`NamespacedType`](https://github.com/ros2/rosidl/blob/master/rosidl_parser/rosidl_parser/definition.py#L169) for input arg. `NamespacedType` expects as input args `Iterable[str], str`.

`NamespacedType` has base [`AbstractNestableType`](https://github.com/ros2/rosidl/blob/master/rosidl_parser/rosidl_parser/definition.py#L111) whereas the '`__slots__`' `value_type` comes from [`AbstractNestedType`](https://github.com/ros2/rosidl/blob/master/rosidl_parser/rosidl_parser/definition.py#L285). Am I missing something or is it a bug ?

**Comment by dirk-thomas** [comment]
I would guess the annotation is just wrong. This is how it is being used:

https://github.com/ros2/rosidl_python/blob/6ec55cbcc7cc4e517eb808567ba2b742d612d3ae/rosidl_runtime_py/rosidl_runtime_py/set_message.py#L52-L53

Maybe @mikaelarguedas can comment since he wrote this in #33.

**Comment by mikaelarguedas** [comment]
Yeah that's definitely a bug. I must have mixed up the types when rebasing/updating #33.

See #74 for a fix making the function behave as specified
